version: "3.8"

services:

  twitter-app-database:
    container_name: twitter-app-database
    image: mysql:8
    ports:
      - "${DB_PORT}:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-volume:/var/lib/mysql

  twitter-app-backend:
    container_name: twitter-app-backend
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    restart: always
    volumes:
      - ./src/backend:/var/www/html/
    depends_on:
      - twitter-app-database
    links:
      - twitter-app-database

  twitter-app-api-proxy:
    container_name: twitter-app-api-proxy
    image: nginx:alpine
    restart: always
    ports:
      - "3007:80"
    volumes:
      - ./src/backend:/var/www/html/
      - ./src/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - twitter-app-backend
    links:
      - twitter-app-backend

  twitter-app-frontend:
    container_name: twitter-app-frontend
    restart: always
    build:
      dockerfile: ./docker/frontend/Dockerfile
      context: .
    volumes:
      - ./src/frontend:/app
      - /app/node_modules
      - /app/build
      - /app/cache
    ports:
      - 3008:3000
    depends_on:
      - twitter-app-api-proxy

volumes:
  db-volume:
